about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("new/", views.new_post, name="new_post"),
    path("<str:username>/", views.profile, name="profile"),
    path("<str:username>/<int:post_id>/", views.post_view, name="post"),
    path("<str:username>/<int:post_id>/edit/",
         views.post_edit, name="post_edit"),
]

users/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Оглавление',
                             help_text='Оглавление группы')
    slug = models.SlugField(unique=True, verbose_name='URL',
                            help_text='URL для группы')
    description = models.TextField(verbose_name='Описание',
                                   help_text='Описание группы')

    class Meta:
        verbose_name_plural = 'Сообщества'
        verbose_name = 'Сообщество'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст',
                            help_text='Текст поста')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Автор', related_name='posts',
                               help_text='Автор поста')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True,
                              verbose_name='Группа', related_name='posts',
                              null=True, help_text='Ссылка на группу')

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def __str__(self):
        return self.text[:15]

posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text')
        labels = {
            'text': 'Текст',
            'group': 'Группа',
        }

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class UserCreation(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django. contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import Post, Group, User
from .forms import PostForm
from yatube.settings import TEN_POSTS


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, TEN_POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'paginator': paginator}
    return render(request, 'index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, TEN_POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'group': group, 'page': page, 'paginator': paginator}
    return render(request, 'group.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    author_posts = author.posts.all()
    paginator = Paginator(author_posts, TEN_POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'author': author,
        'author_posts': author_posts,
        'paginator': paginator,
    }
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    context = {
        'author': post.author,
        'post': post,
    }
    return render(request, 'post.html', context)


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)

    group = post.group

    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('post', username=post.author.username, post_id=post.id)

    context = {
        'post': post,
        'group': group,
        'form': form
    }
    return render(request, 'post_edit.html', context)


@login_required
def new_post(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('index')

    context = {'form': form}
    return render(request, 'new_post.html', context)

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import UserCreation


class SignUp(CreateView):
    form_class = UserCreation
    success_url = reverse_lazy('signup')
    template_name = 'signup.html'

templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Об Авторе
                </div>
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Полезный короткий текст
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">
          <div class="card-text">
            <p>Текст страницы "Об Авторе"</p>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

templates/about/tech.html
{% extends "base.html" %}
{% block title %}О Технологиях проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  О Технологиях
                </div>
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Полезный короткий текст
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">
          <div class="card-text">
            <p>Текст страницы "О Технологиях"</p>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

templates/base.html
<!doctype html>
<html>
  <head>
  	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  	<title>{% block title %}The Last Social Media You will Ever Need{% endblock %} | Yatube</title>
  	{% load static %}
  	<link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
  	<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
  	<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    {% include 'includes/nav.html' %}
    <main>
      <div class="container">
        <h1>{% block header %}The Last Social Media You will Ever Need{% endblock %}</h1>
        {% block content %}

        {% endblock %}
      </div>
    </main>
    {% include 'includes/footer.html' %}
  </body>
 </html>
 

templates/group.html
{% extends 'base.html' %}


{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}

{% block header %}{{ group.title }}{% endblock %}
{% block content %}
  <p>{{ group.description }}</p>

  {% for post in page %}
    <h3>
      Автор: {{ post.author.get_full_name }}, дата публикации:
      {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    <hr>
  {% endfor %}

  {% include 'includes/paginator.html' %}
  
{% endblock %}

templates/includes/author_card.html
<div class="card">
    <div class="card-body">
      <div class="h2">
        <!-- Имя автора -->
        {{ author.get_full_name }}
      </div>
      <div class="h3 text-muted">
        <!-- username автора -->
        {{ author.username }}
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="h6 text-muted">
          Подписчиков: XXX <br />
          Подписан: XXX
        </div>
      </li>
      <li class="list-group-item">
        <div class="h6 text-muted">
          <!--Количество записей -->
          Записей: {{ post.count }}
        </div>
      </li>
    </ul>
  </div>

templates/includes/card.html
<div class="card">
    <div class="card-body">
      <div class="h2">
        <!-- Имя автора -->
        {{ author.get_full_name }}
      </div>
      <div class="h3 text-muted">
        <!-- username автора -->
        {{ author.username }}
      </div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="h6 text-muted">
          Подписчиков: XXX <br />
          Подписан: XXX
        </div>
      </li>
      <li class="list-group-item">
        <div class="h6 text-muted">
          <!--Количество записей -->
          Записей: {{ post.count }}
        </div>
      </li>
    </ul>
  </div>

templates/includes/card_0.html
<!-- Пост -->  
<div class="card mb-3 mt-1 shadow-sm">
    <div class="card-body">
      <p class="card-text">
        <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
        <a href="{% url 'profile' author.username %}"><strong class="d-block text-gray-dark">@{{ author.username }}</strong></a>
          <!-- Текст поста -->
          {{ post.text }}
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group ">
          <!-- Ссылка на редактирование, показывается только автору записи -->
          {% if user == author %}
            <a class="btn btn-sm text-muted" href="{% url 'post_edit' author.username post.id %}" role="button">Редактировать</a>
          {% endif %}
        </div>
          <!-- Дата публикации  -->
          <small class="text-muted">{{ post.pub_date }}</small>
      </div>
    </div>
</div>

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе сайта</a> - 
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
  <p class="m-0 text-dark text-center">
    Социальная сеть 
    <span style="color:red">Ya</span>tube © {% now "Y" %}, все права защищены.
  </p>
</footer>

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
      Пользователь: {{ user.username }}.
      <a class="p-2 text-dark" href="{% url 'new_post' %}">Создать новую запись</a>
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

templates/includes/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">&laquo; Предыдущая</span>
      </li>
    {% endif %}

    {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="page-item active">
          <span class="page-link">{{ i }}
            <span class="sr-only">(текущая)</span>
          </span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Следующая &raquo;</span>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/includes/post_card.html
<!-- Пост -->  
<div class="card mb-3 mt-1 shadow-sm">
    <div class="card-body">
      <p class="card-text">
        <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
        <a href="{% url 'profile' author.username %}"><strong class="d-block text-gray-dark">@{{ author.username }}</strong></a>
          <!-- Текст поста -->
          {{ post.text }}
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group ">
          <!-- Ссылка на редактирование, показывается только автору записи -->
          {% if user == author %}
            <a class="btn btn-sm text-muted" href="{% url 'post_edit' author.username post.id %}" role="button">Редактировать</a>
          {% endif %}
        </div>
          <!-- Дата публикации  -->
          <small class="text-muted">{{ post.pub_date }}</small>
      </div>
    </div>
</div>

templates/index.html
{% extends 'base.html' %}


{% block title %}Последние обновления на сайте.{% endblock %}
{% block header %}Последние обновления на сайте.{% endblock %}
{% block content %}
  {% for post in page %}
    <h3>
      Автор: {{ post.author.get_full_name }}, дата публикации {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>
      {{ post.text|linebreaksbr }}
    </p>
    <hr>
  {% endfor %}

  {% include 'includes/paginator.html' %}
  
{% endblock %}

templates/new_post.html
{% extends 'base.html' %}
{% block title %}Новый пост{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Создание нового поста</div>
      <div class="card-body">
        {% for error in form.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
        {% endfor %}

        <form method="post">
        {% csrf_token %}
        
        {% for field in form %}
          <div class="form-group row" aria-required={% if field.field.required %}
          "true"{% else %}"false"{% endif %}>
            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required">*</span>
              {% endif %}
            </label>
            <div class="col-md-6">
            
              {{ field|addclass:"form-control" }}

              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          </div>
        {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Создать новый пост
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/post.html
{% extends 'base.html' %}

{% block title %}Просмотр записи{% endblock %}
{% block header %}Просмотр записи{% endblock %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      {% include 'includes/author_card.html' %}
    </div>

    <div class="col-md-9">
      {% include 'includes/post_card.html' %}
    </div>
  </div>
</main>

{% endblock %}

templates/post_edit.html
{% extends 'base.html' %}
{% block title %}Редактирование поста{% endblock %}
{% block header %}Редактирование поста{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Редактирование поста</div>
      <div class="card-body">
        {% for error in form.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
        {% endfor %}

        <form method="post">
        {% csrf_token %}
        
        {% for field in form %}
          <div class="form-group row" aria-required={% if field.field.required %}
          "true"{% else %}"false"{% endif %}>
            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required">*</span>
              {% endif %}
            </label>
            <div class="col-md-6">
            
              {{ field|addclass:"form-control" }}

              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          </div>
        {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Изменить пост
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block title %}Профиль пользователя{% endblock %}
{% block header %}Профиль пользователя{% endblock %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      {% include 'includes/author_card.html' %}
    </div>

    <div class="col-md-9">
      <!-- Начало блока с отдельным постом --> 
      {% for post in page %}
        {% include 'includes/post_card.html' %}
      {% endfor %}
      
      {% include 'includes/paginator.html' %}
      </div>
    </div>
</main>

{% endblock %}

users/templates/signup.html
{% extends 'base.html' %}

{% extends 'base.html' %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Зарегистрироваться</div>
      <div class="card-body">

        {% for error in form.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error }}
          </div>
        {% endfor %}

        <form method="post" action="{% url 'signup' %}">
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row" aria-required={% if field.field.required %}
            "true"{% else %}"false"{% endif %}>
              <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required">*</span>
                {% endif %}
              </label>
              <div class="col-md-6">
                
                {{ field|addclass:"form-control" }}

                {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}